services:
  - type: web
    name: cown1-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: MYSQL_HOST
        value: localhost
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: ""
      - key: MYSQL_DATABASE
        value: cown1_db
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: MONGODB_URI
        value: mongodb://localhost:27017/cown1
      - key: NEO4J_URI
        value: bolt://localhost:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        value: password
